import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css"

import { Vazirmatn } from "next/font/google";

const vazir = Vazirmatn({
    subsets: ["arabic", "latin"],
    display: "swap",
});

export const metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa-IR" dir="rtl" className={vazir.className}>
            <body>{children}</body>
        </html>
    );
}
